# Generated by Django 3.0.3 on 2020-02-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='counts',
        ),
        migrations.AddField(
            model_name='post',
            name='counts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
